### ISSUE TITLE
use `--json` to get status

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [maxgallup/tailscale-status#1]
Using the `tailscale status --json` would be more convenient than manually parsing the output. It would also prevent this bug

![image](https://user-images.githubusercontent.com/15961647/171032733-a15979e3-96b2-4178-bc38-e6a84a82b884.png)

All my nodes get detected as my own computer because there hasn't been any traffic yet. The json output has separate fields for `Self` and `Nodes`.

**Comment by maxgallup** [comment]
Hey, thanks for the advice!

The latest commit uses `--json` like you recommended, let me know if it fixes your issue!

**Comment by SoMuchForSubtlety** [comment]
Thanks :)
