### ISSUE TITLE
Systray icons shows without green border until first clicked after reboot even those TS active

### ISSUE THREAD

**Issue by sitepodmatt** [maxgallup/tailscale-status#15]
![image](https://user-images.githubusercontent.com/1687145/190840149-4d9674de-8845-4488-a26e-e7c6f69baecb.png)

I have to click the icon to trigger to green border. I suspect possibly the extension loads before tailscale resumes its up state? 

  ~ tailscale --version
1.30.2
  tailscale commit: 24c524c7853b15ca4b33d085e6c5253bd4cd508e
  other commit: c399ae6fad6583b332f17e081f40667c055e9149
  go version: go1.19.1-tsb13188dd36

  ~ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

**Comment by sitepodmatt** [comment]
Also remains green if I tailscale down from cli.

Is it possible to poll for the state every X seconds somehow maybe like 

```
DATA=$(curl --silent --unix-socket /run/tailscale/tailscaled.sock http://localhost/localapi/v0/status)

BACKENDSTATE=$(echo "$DATA" | jq -r .BackendState)

```
this returns running if active

**Comment by krptg0** [comment]
+1 on that "bug"

**Comment by maxgallup** [comment]
Sorry for the late reply on this issue and thanks for the suggestions!

I think that accessing the status via the localapi is the same as running `tailscale status --json` which I've been using so far to get the status, however I added it anyway to see if it would help with #13. 

Also added a timer for every 10 seconds to update the menu icons and the drop down menu. (don't know what good practice is on how long this interval is, suggestions welcome!)

Update will be added to gnome extensions soon, thanks.
