### ISSUE TITLE
Latest update breaks the extension on gnome 42 

### ISSUE THREAD

**Issue by rnagabhyrava** [maxgallup/tailscale-status#16]
![Screenshot from 2022-09-18 12-01-20](https://user-images.githubusercontent.com/34751450/190919307-851a0650-d5b4-4df0-9697-8e09cdfd6026.jpg)

Love this extension but getting this error with latest update as of Sep 18 on debian testing gnome 42.4

**Comment by leochras** [comment]
Confirmed on arch Gnome 42.5

**Comment by bclouthier** [comment]
Yes I can also confirm the latest update breaks the extension. Fedora 36 on Gnome 42.4 with Tailscale Status 13?

**Comment by rnagabhyrava** [comment]
Opened a PR #17  with quick fix. In the meantime, if anyone want to try it out you can delete the existing extension and clone my repo https://github.com/rnagabhyrava/tailscale-status and paste the entire folder "tailscale-status@maxgallup.github.com" into ".local/share/gnome-shell/extensions/". I did not change UUID so this should catch the next update as the original.

**Comment by leochras** [comment]
> Opened a PR #17 with quick fix. In the meantime, if anyone want to try it out you can delete the existing extension and clone my repo https://github.com/rnagabhyrava/tailscale-status and paste the entire folder "tailscale-status@maxgallup.github.com" into ".local/share/gnome-shell/extensions/". I did not change UUID so this should catch the next update from gnome extensions.

This fix worked for me, thank you!

**Comment by maxgallup** [comment]
Thanks @rnagabhyrava @bclouthier @leochras for catching this. Was a bit too busy past few days and this had slipped right under my nose. Official gnome extension will be updated with the fix.
