### ISSUE TITLE
Option for --accept-routes

### ISSUE THREAD

**Issue by galettof** [maxgallup/tailscale-status#2]
First off, thank you for this! I tried it on Fedora 36 with Gnome 42.2 and it works great.

Instead of
`sudo tailscale up`
I need to run
`sudo tailscale up --accept-routes`

I understand the code enough to permanently change the 'up' command to suit my needs. Unfortunately, my programming skills are limited so I don't know how to do this, but perhaps a menu option to turn `--accept-routes` on and off might be a useful addition.

Cheers!

**Comment by maxgallup** [comment]
Hey,
I've created a branch **feature-AcceptRoutes** with this implemented. Try downloading the code from that branch and install the extension (move the _tailscale-status@maxgallup.github.com_ directory into _~/.local/share/gnome-shell/extensions/_  and reload the gnome shell with Alt + F2 and enter "r" as the command). Let me know if this suits your needs and then I'll merge it to the main branch.

Thanks for the feedback!

**Comment by galettof** [comment]
I tried it and it appears to be working. Thank you very much!

**Comment by maxgallup** [comment]
Great!
