### ISSUE TITLE
FR: support switching between multiple accounts

### ISSUE THREAD

**Issue by arunoruto** [maxgallup/tailscale-status#24]
Since version `1.34` tailscale supports switching between multiple accounts on a single machine. It would be nice to fetch the output of `tailscale switch --list` and get a list in the tray to switch between the accounts.

**Comment by maxgallup** [comment]
@arunoruto The latest commit (update soon available via gnome extensions) added this. Let me know if you have any suggestions for improvements!

**Comment by arunoruto** [comment]
Thanks a lot! Works for now really good 😁
