### ISSUE TITLE
Option to have : Shield up & lan acceptation

### ISSUE THREAD

**Issue by BirdInFire** [maxgallup/tailscale-status#3]
I would like to have Shield up option and lan acception added to a config (for when we clic on tailscale up)

Thanks

**Comment by maxgallup** [comment]
Hey,
I will add the `shield up` option. However, could you explain what exactly you mean with "lan acception added to a config"?

Cheers

**Comment by BirdInFire** [comment]
> Hey, I will add the `shield up` option. However, could you explain what exactly you mean with "lan acception added to a config"?
> 
> Cheers

Hello, I tanlk about this cli command : 

`--exit-node-allow-lan-access` Allow direct access to the local network when routing traffic via an exit node. Defaults to not allowing direct access to your LAN.

sources : https://tailscale.com/kb/1080/cli/#command-reference

**Comment by maxgallup** [comment]
Both options have been added, let me know if you encounter any issues!
