### ISSUE TITLE
FR: Allow copying hostname and MagicDNS URL in "Nodes" dropdown

### ISSUE THREAD

**Issue by Tc-001** [maxgallup/tailscale-status#32]
Currently only IP addresses are copy-able, it would be nice if that could be tweaked to also allow hostnames and/or URLs, as they are easier to work with in web and SSH.

**Comment by maxgallup** [comment]
Unfortunately the gnome drop down is a bit limited in that regard and I couldn't think of a way to add this without impacting the usability of the current UI. Sorry!
