### ISSUE TITLE
Question - Allow Direct LAN access

### ISSUE THREAD

**Issue by yuriw** [maxgallup/tailscale-status#40]
I tried to enable `Allow Direct LAN access` and got a message to set up an exit node first.

I do have an exit node setup.

What's is going on? And what does actually `Allow Direct LAN access` do?

**Comment by tmuncks** [comment]
You are probably looking for the documentation for tailscale itself, for that explanation:

https://tailscale.com/kb/1103/exit-nodes/

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Yuri Weinstein ***@***.***>
Sent: Saturday, September 30, 2023 1:38:31 PM
To: maxgallup/tailscale-status ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [maxgallup/tailscale-status] Question - Allow Direct LAN access (Issue #40)


I tried to enable Allow Direct LAN access and got a message to set up an exit node first.

I do have an exit node setup.

What's is going on? And what does actually Allow Direct LAN access do?

**Comment by ZenFisher** [comment]
This appears to be a bug in tailscale. With an exit-node set, the toggle is not working correctly. 

With an exit-node set all IP traffic from your system is routed thru the exit-node.
This terminal command will allow your system to connect with other systems on your local lan.
sudo tailscale set --exit-node-allow-lan-access=true

**Comment by jimeh** [comment]
This still seems to be a bug with Tailscale Status. While the command @ZenFisher mentioned works, it's a workaround, and it would be nicer if the toggle in the UI worked :)

**Comment by skillz-xx** [comment]
yup, still a bug, doesnt work with local network sharing. no way to turn it on (which sucks)
