### ISSUE TITLE
Sorting the Exit Nodes list

### ISSUE THREAD

**Issue by ZenFisher** [maxgallup/tailscale-status#42]
It would be fantastic to get the exit node list sorted to make it quicker to choose a node by country.

**Comment by maxgallup** [comment]
So just to be clear you're referring to a lexicographical ordering on the hostnames of the devices?

**Comment by glidingthrough** [comment]
Especially relevant for those of us who use Mullvad exit nodes, where 100+ exit nodes are listed

**Comment by maxgallup** [comment]
A new update has been released, let me know if this works well for you.

**Comment by glidingthrough** [comment]
Sorted by first character, alphabetically, but not the second, third, fourth, etc.

See sample screenshot below.

![Screenshot from 2023-12-20 20-17-41](https://github.com/maxgallup/tailscale-status/assets/97669346/9fca3ecc-0425-44c7-89d4-6165030cf26b)

**Comment by maxgallup** [comment]
Ah, has been patched and updated.

**Comment by glidingthrough** [comment]
Thanks for your efforts!

Currently running version 26 - now all are jumbled up:

![Screenshot from 2023-12-26 12-16-06](https://github.com/maxgallup/tailscale-status/assets/97669346/a25a5a1a-010b-4aed-b759-587463d1546e)

**Comment by maxgallup** [comment]
Oh, sorry it slipped by me as I was zipping files for submission. Now it should be correct :+1:

**Comment by glidingthrough** [comment]
Works beautifully - thank you!!

![Screenshot from 2023-12-27 15-25-56](https://github.com/maxgallup/tailscale-status/assets/97669346/4622615f-f1b0-4c94-85c2-00c5bd0db860)
