### ISSUE TITLE
CPU Spikes & Brief System Freezes

### ISSUE THREAD

**Issue by glidingthrough** [maxgallup/tailscale-status#44]
I realised only today - after several months of usage - that this extension is what has been causing my system to freeze for a second or two, every 10 seconds when the extension does its refresh. Makes watching videos pretty intolerable. Not sure what can be done to fix the issue, but thought I should flag it here so you are aware.

**Comment by maxgallup** [comment]
Could you specify what OS and gnome version you're using?

**Comment by glidingthrough** [comment]
Fedora Silverblue 39, Gnome 45.2

**Comment by geoffeg** [comment]
This appears to be related to Mullvad exit nodes. When I enabled it for the system I have the extension installed on I started noticing the freezes. Ubuntu 22.04, tailscale 1.56.1.

**Comment by glidingthrough** [comment]
I can confirm that I, too, use Mullvad exit nodes. Perhaps the extension is refreshing the exit node list and, when it's a significant list, it causes a CPU spike?

**Comment by maxgallup** [comment]
Perhaps you could try setting the refresh timeout in the settings to 0?

**Comment by glidingthrough** [comment]
Seems to work! Thanks :)

Are there any known repercussions in the extension's functionality resulting from setting it to 0?

**Comment by maxgallup** [comment]
In the latest update I decided to actually remove this refresh as it's not necessary and solves the mulvad issue.
