### ISSUE TITLE
FR: Add tailscale drop feature

### ISSUE THREAD

**Issue by BirdInFire** [maxgallup/tailscale-status#5]
Can you (please) add trailscale drop feature in it ?
There is one extension already but they don't have updated to support gnome 42 :/

**Comment by maxgallup** [comment]
I've added a basic (naive) way to send and receive files. Feedback welcome!

**Comment by BirdInFire** [comment]
> I've added a basic (naive) way to send and receive files. Feedback welcome!

Thanks will try it tomorrow (or today if updated on gnome extension)
