### ISSUE TITLE
Feature request: More icons

### ISSUE THREAD

**Issue by krptg0** [maxgallup/tailscale-status#8]
Hi, 

Thanks for that great extension, that's everything I wanted for a GUI for tailscale !
If you want to add it to the README: can confirm it works on Gnome 42 (Wayland) on Ubuntu 22.04.

I wanted to ask if you could change the icon based on the status of tailscale as per the Windows client :
- Icon with 4 white dots when tailscale is up
- Icon with all grey dots when tailscale is down
- Icon with an arrow when an exit node is enabled
- Maybe other icons when incoming file is turned on ?

Thank you again :)

**Comment by krptg0** [comment]
Hi,

The "tailscale down" is like this one :
![image](https://user-images.githubusercontent.com/45569465/183284516-21593a60-bfd3-4900-8b3f-d95d6e295360.png)

Unfortunatly I can't find the exit node icon, without access to a Windows install :/

**Comment by maxgallup** [comment]
I've released an update with the 3 different icons for when the status is up, down, or up with an exit-node. I'm not very experienced with graphic design so suggestions or pull requests are welcome. :)
